### ISSUE TITLE
Proper way to install menu-cache plugin?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [inpsyde/menu-cache#4]
I created a composer.json in my wordpress directory (/var/www/mysite.com):

```
{
    "require": {
        "inpsyde/menu-cache": "^1.3"
    }
}
```

When I run composer install, the plugin is installed in /var/www/mysite.com/vendor instead of /var/www/mysite.com/wp-content/plugins.

What is the correct way to install this plugin?

**Comment by szepeviktor** [comment]
[Here](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/composer.json#L19-L29) I call it `static` but you'll find out.

**Comment by szepeviktor** [comment]
If you *attack* a non-composer WP install then simply use [vendor-dir](https://getcomposer.org/doc/06-config.md#vendor-dir)

**Comment by ahmed-sigmalux** [comment]
Your links pointed me in the right direction.

Thanks!
