### ISSUE TITLE
Menu key argument clarity?

### ISSUE THREAD

**Issue by lkraav** [inpsyde/menu-cache#7]
Documentation is a bit unclear on how or why would you actually use `MenuCache::FILTER_KEY_ARGUMENT`?

On surface, it seems like working with `MenuCache::FILTER_KEY` is always better.

Anything I'm missing?

**Comment by tfrommen** [comment]
This is basically for the rare case of a plugin/naming conflict. The argument name defaults to `menu_key`. The value is set by the Menu Cache plugin. Now assume there was another plugin (or maybe even the theme, for whatever reason) that already adds a `menu_key` property to the menu arguments array. See the conflict? 🙂

**Comment by lkraav** [comment]
I do see the conflict. Alles klar.

**Comment by gmazzap** [comment]
Thanks @tfrommen and @lkraav 

Seems this is sorted out so I'm closing it... Feel free to reopen if needed.
